title: Home Assistant
resources: !include lovelace/includes/resources.yaml

# custom_header:
#   compact_mode: true
#   voice_hide: true
#   hide_help: true
#   hide_config: true
#   chevrons: false
#   shadow: false

#   background: var(--app-header-background-color)
#   elements_color: var(--app-header-text-color)
#   active_tab_color: var(--state-icon-active-color)
#   tab_indicator_color: var(--state-icon-active-color)

button_card_templates: !include lovelace/includes/button_card_templates.yaml

views: !include_dir_list lovelace/views/