homeassistant:
  customize:
    package.node_anchors:
      common: &common
        package: "doorsensors"

    binary_sensor.outside_door_group_contact:
      <<: *common
      friendly_name: Buitendeuren
      device_class: door

  customize_glob:
    sensor.*_doorsensor*:
      <<: *common
    binary_sensor.*_doorsensor*:
      <<: *common
  
binary_sensor:
  - platform: template
    sensors:
      outside_door_group_contact:
        value_template: >-
            {{ is_state('binary_sensor.front_door_doorsensor_contact', 'on')
               or is_state('binary_sensor.livingroom_doorsensor_2_contact', 'on') }}